### ISSUE TITLE
回文判断可以用manacher算法去实现，o(N),╰(￣▽￣)╮

### ISSUE THREAD

**Issue by DashShen** [zxwtry/document#1]
god v(伟神就是厉害，github的贡献强都是天天是满的）

**Comment by zxwtry** [comment]
@DashShen  
我是水货。。。天天在水(＠_＠;)  
被达神issue，受宠若惊中(๑•̀ㅂ•́)و✧

**Comment by DashShen** [comment]
哈哈哈，加油看好你
